create table human (
  userid                        bigint generated by default as identity (start with 1)  not null,
  first_name                    varchar(255),
  last_name                     varchar(255),
  gender                        varchar(255),
  age                           integer not null,
  constraint pk_human primary key (userid)
);

