/*package com.jpa.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class MemoryHSQLDB {

	private static MemoryHSQLDB INSTANCE ;
	private static final String CREATE_TABLE = "CREATE TABLE human(id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY , " +
			"first_name varchar(50), last_name varchar(50), gender varchar(50), age integer);";

	private MemoryHSQLDB(){
	    try {
	    	Class.forName("org.hsqldb.jdbcDriver");
			Connection conn = DriverManager.getConnection("jdbc:hsqldb:mem:aname", "sa", "");
			Statement stmnt = conn.createStatement();
			stmnt.execute(CREATE_TABLE);
	    } catch (SQLException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}

	public synchronized static MemoryHSQLDB getInstance(){
		if(INSTANCE == null){
			INSTANCE = new MemoryHSQLDB();
		}
		System.out.println("Got Instance as : " + INSTANCE);
		return INSTANCE;
	}
}
*/